const express = require('express')
const router = express.Router()
const auth = require('../middleware/check-auth')
const profileController = require('../controllers/profileController')

router.post('/signup', profileController.user_signup)
router.post('/login', profileController.user_login)
router.delete('/delete/profileid',auth ,profileController.user_delete)
router.get('/bills/:profileid', auth,profileController.get_all_bills)
router.get('/bills/:profileid/:billid', auth, profileController.get_specific_bill)
router.post('/bills/:profileid', auth, profileController.create_bill)
router.post('/bills/:profileid/:billid', auth, profileController.update_bill)
router.delete('/bills/:profileid/:billid', auth, profileController.delete_bill)
router.get('/income/:profileid', auth,profileController.get_all_income)
router.get('/income/:profileid/:incomeid', auth, profileController.get_specific_income)
router.post('/income/:profileid', auth, profileController.create_income)
router.post('/income/:profileid/:incomeid', auth, profileController.update_income)
router.delete('/income/:profileid/:incomeid', auth, profileController.delete_income)
router.get('/savings/:profileid', auth,profileController.get_all_savings)
router.get('/savings/:profileid/:savingsid', auth, profileController.get_specific_savings)
router.post('/savings/:profileid', auth, profileController.create_savings)
router.post('/savings/:profileid/:savingsid', auth, profileController.update_savings)
router.delete('/savings/:profileid/:savingsid', auth, profileController.delete_savings)
router.get('/expenses/:profileid', auth,profileController.get_all_expenses)
router.get('/expenses/:profileid/:expensesid', auth, profileController.get_specific_expenses)
router.post('/expenses/:profileid', auth, profileController.create_expenses)
router.post('/expenses/:profileid/:expensesid', auth, profileController.update_expenses)
router.delete('/expenses/:profileid/:expensesid', auth, profileController.delete_expenses)
module.exports = router